#!/bin/bash

# allow time for pandoc to compile
sleep 0.5

# html file needs to have a title for this to work properly
filename="$1"

# get the title of the html file to match with xprop info
title=$(awk -vRS="</title>" '/<title>/{gsub(/.*<title>|\n+/,"");print;exit}' "$1")
# echo "title: $title"

browser='firefox'
# browser='google-chrome'

# from `xprop`
if [ $browser == "firefox" ]
then
    # note that the string is not a minus, it is something unicode
    # window_title="${title} — Mozilla Firefox"
    # # Firefox changed title in newer versions
    window_title="${title} — Original profile — Mozilla Firefox"
else
    window_title="${title} - Google Chrome"
fi


# echo "title: ${window_title}" >> $HOME/found_windows
# echo $(xdotool search --name "${window_title}") >> $HOME/found_windows
#

window_id=$(xdotool search --name "${window_title}" | head -1)

## Debug print
# echo "filename = $filename"
# echo "title = $title"
# echo "window-title = $window_title"
# echo "window_id = $window_id"

if [ $window_id ]
then
     # echo "already open"
     
     # xdotool search --desktop $1 --name "${window_title}" windowactivate 
     # xdotool key 'F5' > /dev/null 2>&1

     # send keypress without focusing
     xdotool key --window ${window_id} 'F5'
else
    # echo "launching"
    $browser --new-window ${1} & 
fi

