#!/bin/bash
# i3-msg rename workspace to 'linalg'

path="$HOME/teaching/2025-Spring/215-Spring-2025"
# book="$HOME/Downloads/Richard L. Burden, J. Douglas Faires - Numerical Analysis, 9th Edition -Brooks Cole (2010).pdf"
book="$HOME/Downloads/LinearAlgebra.pdf"
mat1="$HOME/Downloads/Jenny-Math215S24/"
mat2="$HOME/Downloads/Joshua-Linear-Algebra"

# cd "$path"
i3-msg layout stacking &
zathura "$book" & 
xfce4-terminal -e "ranger $mat1" &
xfce4-terminal -e "ranger $mat2" &
cd "$path"
xfce4-terminal -e "ranger" &
i3-msg move left

