#! /bin/bash

echo "Hello $1"
## downloaded dark gruvbox-gtk3 theme from
## https://github.com/bennetthardwick/gruvbox-gtk
## and move it to /usr/share/themes

## The first argument should be dark or light
## I have named the required files accordingly

## setting up the theme name and term color name
Term="gruvbox-$1"
#GTK3 theme location: /usr/share/themes, downloaded from git
# local (in .local/share/themes) themes do not work well, not sure why
GUI="oomox-gruvbox-$1"	

#######################################################################
## Terminal colorscheme
termconf_loc=$HOME/.config/xfce4/terminal
filename=$termconf_loc/colorschemes/$Term.theme
if ! [[ -f $filename ]]
then
    echo "No such colorscheme: $filename"
    #exit 1
else
    # copy the non-color settings part
    cp $termconf_loc/{terminalrc.settings,.terminalrc.tmp}
    # copy the color settings part
    cat "$termconf_loc/colorschemes/$Term.theme" >> $termconf_loc/.terminalrc.tmp

    # copy the newly generated config file
    # sourcing the file happens automatically on edit
    mv $termconf_loc/{.terminalrc.tmp,terminalrc}
fi

#######################################################################
## i3 colorscheme
#Term="gruvbox-$1"

i3_loc=$HOME/.config/i3
filename=$i3_loc/$Term.config
if ! [[ -f  $filename ]]
then
    echo "No such colorscheme: $filename"
    #exit 1
else
    # copy the non-color settings part
    cp $i3_loc/{config.base,.config.tmp}
    # copy the color settings part
    cat "$i3_loc/$Term.config" >> $i3_loc/.config.tmp

    # copy the newly generated config file
    # sourcing the file happens automatically on edit
    mv $i3_loc/{.config.tmp,config}

    # reload
    i3-msg reload
fi

#######################################################################
## Applying the GUI theme
xfconf-query -c xsettings -p /Net/ThemeName -s $GUI

#######################################################################
## Editing vim settings

# Save the vim variable, so that we can load it from .vimrc
echo "set background=$1" 
echo "set background=$1" > $HOME/.vim/vimtheme
# sending remote commands to all running servers to source the new vimrc
# this works under the assumption that I will always run vim in server mode
for f in $(vim --serverlist)	# loop through all the running servers
    	# only source the background part
	do vim --servername $f --remote-send '<ESC>:source $HOME/.vim/vimtheme<CR>'
done

#######################################################################
# if request for full update, i.e. awesome restart
## Doesn't work now
##  * We need to find better ways to change color without restarting awesome
##  * We need to find a way to dynamically change the variable colortheme in theme-debdeep.lua
#if [ "$2" == "full" ]
#then
	### restart awesome after swapping the files
	#awmtheme=$HOME/.config/awesome/themes/powerarrow/
	#cp $awmtheme/theme-debdeep-$1.lua $awmtheme/theme-debdeep.lua
	#echo 'awesome.restart()' | awesome-client 
#fi
