#!/bin/bash

get_packages(){

    min="vim vim-gtk3 zathura ranger xdotool git openssh-server htop powertop unclutter redshift mplayer sxiv xbacklight exuberant-ctags suckless-tools i3 rofi i3blocks py3status tmux xfce4-goodies blueman compton"
    code="python3-pip pandoc docker.io nodejs npm"
    soft="gimp xournal cheese"
    tex="texlive-latex-recommended texlive-pictures texlive-xetex latexmk texlive-science"

    pkglist="$min $code $soft $tex"

    echo "installing packages: $1"
    sudo apt-get update
    sudo apt-get --assume-yes install $pkglist
}

#######################################################################
# debian packages

get_chrome(){
    echo 'installing google-chrome'
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome-stable_current_amd64.deb
    rm google-chrome-stable_current_amd64.deb
}

get_zoom(){
    echo 'installing zoom'
    wget https://zoom.us/client/latest/zoom_amd64.deb
    #sudo apt-get install libgl1-mesa-glx -y # dependency, added to packages
    sudo dpkg -i zoom_amd64.deb
    rm zoom_amd64.deb
}

get_skype(){
    echo 'installing skype'
    wget https://go.skype.com/skypeforlinux-64.deb
    sudo dpkg -i skypeforlinux-64.deb 
    rm skypeforlinux-64.deb
}

get_debs(){
	get_chrome
	get_zoom
	get_skype
}

#get_theme(){
    #echo 'installing gruvbox-gtk theme from git to use `themeset dark`'
    #git clone https://github.com/3ximus/gruvbox-gtk
    #sudo cp -r gruvbox-gtk /usr/share/themes/
#}

#######################################################################
# vim and config setup
setup_vim(){
    echo 'installing nodejs for coc'
    curl -sL install-node.now.sh/lts >> install_nodejs
    chmod +x install_nodejs
    # install locally
    ./install_nodejs --prefix=$HOME/.local

    echo 'installing vim plugins'
    vim +PlugInstall +qall
}

setup_ssh(){
    echo 'generating SSH key'
    ssh-keygen
    eval `ssh-agent -s`
    ssh-add
    ## to copy publickey, print it out
    cat $HOME/.ssh/id_rsa.pub
    echo "Copy key over. Check if connection works with"
    echo "ssh -T git@github.com"
}

get_dotfiles(){
    ### get configs
    git clone https://github.com/debdeepbh/myconfigs.git $HOME/myconfigs
    # copy dotfiles
    cp -r $HOME/myconfigs/dotfiles/. $HOME/
}

## Avoiding very bulky snap, alternatives are preferable
## Install git-like drive for google
#sudo snap install drive pdftk zoom-client

#######################################################################
# gdrive
#

get_drive(){
    ## Install go and then drive
    echo 'installing go'
    go_version="1.17.1"
    wget https://golang.org/dl/go${go_version}.linux-amd64.tar.gz
    rm -rf $HOME/go && tar -C $HOME -xzf go${go_version}.linux-amd64.tar.gz
    rm go${go_version}.linux-amd64.tar.gz
    export PATH=$PATH:$HOME/go:$HOME/go/bin
    ## install drive (download and compile)
    echo 'installing drive'
    go get -u github.com/odeke-em/drive/cmd/drive
    ## move the compiled binary
    mkdir $HOME/.local/bin
    cp $HOME/go/bin/drive $HOME/.local/bin/ #make sure .bashrc has this path included
    ## delete go
    sudo rm -rf $HOME/go
}

setup_drive(){
    # if doesn't exist already
    drive init ~/gdrive
    cd gdrive
    drive pull -no-prompt paper-org book work
}

## Bulky, probably avoid: Install i3 workspace plugin for xfce4-panel
#./install-xfce4-i3-workspace-plugin

## Python and octave stuff
# sudo apt-cache depends octave | grep '[ |]Depends: [^<]' | cut -d: -f2 | tr -d ' ' | xargs sudo apt-get --reinstall install -y
#### Jupyter Lab and octave kernel
## the following code installs the python packages locally
## i.e. in $HOME/.local/share/ 
# pip3 install jupyterlab octave_kernel
## To install it globally and save space in the home directory 
## use `sudo -H`. That way, it installs in /usr/share/ 
#yes | sudo -H pip3 install jupyterlab octave_kernel pandas numpy scipy matplotlib  scikit-learn
# vim keybiniding (a long installation process)
# dependency

# the vim extension
#sudo jupyter labextension install jupyterlab_vim
### Tip: to plot nice plots in octave_kernel, use
# %plot -f svg
# in the beginning of the notebook

## Update the system
#sudo apt-get update -y
#sudo apt-get -y upgrade

### fix-broken
#sudo apt-get -f install

## Install cocalc
get_cocalc(){
    echo 'installing cocalc'
    sudo docker run --name=cocalc -d -v ~/cocalc:/projects -p 443:443 sagemathinc/cocalc
}

setup_zotero(){
    echo 'installing zotero'
    wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
    sudo apt update
    sudo apt install zotero

    echo 'Getting config for gdrive'
    dr=$HOME/gdrive/zotero
    drive pull $dr
    mkdir $HOME/.zotero
    tar -C $HOME/.zotero -xvf $dr/zotero-conf.tar.gz 

    echo 'Getting papers'
    drive pull -no-prompt $HOME/gdrive/paper-org

    echo "Before running sync, check: 1. scihub is off 2. gdrive/paper-org  exists and set in Zotfiles preference..."

    #zotero 
    ## Set firefox default pdf viewer to zathura to set the same for zotero
}

#### Firefox ##############
### Bigger Firefox font
# about:config > devPixelsPerPx to 1.2

#######################################################################

install_existing(){
	echo 'installing for existing functional home directory'
	get_packages
	get_debs
}

install_new(){
	echo 'installing a fully functional setup for an empty home directory'
	get_packages
	get_debs
	setup_vim
	setup_ssh	# requires github setup
	get_dotfiles
	get_drive
	setup_drive
	get_cocalc
	setup_zotero
}

#######################################################################

#install_existing
#install_new

install $1
